<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PC177" failures="1" tests="10" name="TestTemplet.Test_Fax_Templet_A" time="21.770" errors="0" timestamp="2022-12-30T14:52:42 IST" skipped="0">
  <testcase classname="TestTemplet.Test_Fax_Templet_A" name="Templet001_DATE" time="3.047">
    <failure message="expected [12/08/2022] but found [12/30/2022]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [12/08/2022] but found [12/30/2022]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at TestTemplet.Test_Fax_Templet_A.Templet001_DATE(Test_Fax_Templet_A.java:84)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Templet001_DATE -->
  <system-out>
    <![CDATA[ Validating date On Fax]]>
  </system-out>
  <testcase classname="TestTemplet.Test_Fax_Templet_A" name="Templet001_SelectCountry" time="3.542"/>
  <system-out/>
  <testcase classname="TestTemplet.Test_Fax_Templet_A" name="To_TEXT" time="1.873"/>
  <system-out>
    <![CDATA[Form Control Name is clickable and Displayed ]]>
  </system-out>
  <testcase classname="TestTemplet.Test_Fax_Templet_A" name="FormFax_Text" time="2.063"/>
  <system-out/>
  <testcase classname="TestTemplet.Test_Fax_Templet_A" name="Subject_Text" time="2.530"/>
  <system-out/>
  <testcase classname="TestTemplet.Test_Fax_Templet_A" name="Urgent_chechBox" time="1.601"/>
  <system-out/>
  <testcase classname="TestTemplet.Test_Fax_Templet_A" name="PeaseReply_chechBox" time="1.567"/>
  <system-out/>
  <testcase classname="TestTemplet.Test_Fax_Templet_A" name="ForReview_chechBox" time="1.562"/>
  <system-out/>
  <testcase classname="TestTemplet.Test_Fax_Templet_A" name="please_Comment_chechBox" time="1.570"/>
  <system-out/>
  <testcase classname="TestTemplet.Test_Fax_Templet_A" name="Comment_ON_FAX" time="2.415"/>
  <system-out/>
</testsuite> <!-- TestTemplet.Test_Fax_Templet_A -->
